# Generated by Django 4.0.4 on 2022-05-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_owner'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='value_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Value Field'),
        ),
    ]
