# Generated by Django 4.0.4 on 2022-05-03 20:38

import core.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='Owner')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Sub Title')),
                ('slug', models.SlugField()),
                ('body', models.TextField(verbose_name='Body')),
                ('image', models.ImageField(upload_to=core.utils.upload.upload_path, verbose_name='Image')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta Description')),
                ('meta_keyword', models.CharField(max_length=160, verbose_name='Meta Keyword')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'Page',
            },
        ),
    ]
